spring:
  application:
    name: ShoppingKart

  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: create
        #naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


swagger:
  enabled: true


server:
  port: 9000
  servlet:
    context-path: /app
